kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_token
    repo: elit3ge/test
    tags:
    - latest
- name: Docker Hub Description
    uses: peter-evans/dockerhub-description@v3
    with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_token }}
      repository: elit3ge/test
